name: kmeteo
version: '0.1.1'
title: KMeteo
summary: Desktop weather forecasts, current conditions, and maps
description: |
  KMeteo provides current weather conditions and hourly and daily forecasts.
  It includes temperature, pressure, wind speed and direction, sunrise and
  sunset times, plus weather maps.
icon: snap/gui/kmeteo.svg
contact: https://gitlab.com/bitseater/kmeteo
license: GPL-3.0-or-later
issues: https://gitlab.com/bitseater/kmeteo/-/issues
source-code: https://gitlab.com/bitseater/kmeteo
website: https://gitlab.com/bitseater/kmeteo
grade: stable
base: core24
confinement: strict

platforms:
  amd64:
  arm64:

slots:
  dbus-kmeteo:
    interface: dbus
    bus: session
    name: io.gitlab.bitseater.kmeteo

layout:
  /usr/share/icons/hicolor/scalable/status:
    symlink: $SNAP/usr/share/icons/hicolor/scalable/status

apps:
  kmeteo:
    command: usr/bin/io.gitlab.bitseater.kmeteo
    extensions: [kde-neon-6]
    environment:
      PYTHONPATH: $SNAP/usr/share/io.gitlab.bitseater.kmeteo:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/local/lib/python3.12/dist-packages:${PYTHONPATH}
      XDG_DATA_DIRS: $SNAP/usr/share:$SNAP/share:$XDG_DATA_DIRS
      QTWEBENGINE_DISABLE_SANDBOX: "1"
      QT_QPA_PLATFORMTHEM: kde
    common-id: io.gitlab.bitseater.kmeteo
    slots: [dbus-kmeteo]
    plugs:
      - desktop
      - desktop-legacy
      - browser-support
      - icon-themes
      - locale-control
      - network
      - network-status
      - audio-playback
      - opengl
      - wayland
      - x11
      - unity7
      - home
    desktop: usr/share/applications/io.gitlab.bitseater.kmeteo.desktop

parts:
  iconos-propios:
    plugin: dump
    source: .
    stage:
      - usr/share/icons/hicolor/scalable/status/*
  kmeteo-app:
    after: [iconos-propios]
    source: https://gitlab.com/bitseater/kmeteo.git
    source-tag: '0.1.1'
    plugin: meson
    meson-parameters: [--prefix=/usr]
    build-environment:
      - PATH: /usr/bin${PATH:+:$PATH}
    build-packages:
      - gettext
      - appstream
      - desktop-file-utils
      - meson
      - python3
      - python3-pyqt6
      - python3-pyqt6.qtwebengine
      - python3-requests
    stage-packages:
      - python3
      - python3-pyqt6
      - python3-pyqt6.qtwebengine
      - python3-requests
      - hicolor-icon-theme
      - libqt6webenginewidgets6
      - libqt6svg6
      - libasound2t64
      - libnss3